version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gourmet-table-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot-reloading
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    restart: unless-stopped