version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: restaurant-backend
    restart: always
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    networks:
      - restaurant-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: restaurant-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8000
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  static_volume: