version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: restaurant-backend
    restart: always
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    networks:
      - restaurant-network
   

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: restaurant-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8000
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - restaurant-network



  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: restaurant_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  restaurant-network:
    driver: bridge

volumes:
  static_volume:
  db_data: