version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings

volumes:
  static_volume: